function [T,NT]= poisson(Na,lam)
%[T,NT]= poisson(Na,lam)

% lam : lambda of poisson process or arrival rate
% Na : Number of desired arrivals to generate
% T : Times at which arrivals occur (Arrival times)
% NT : Number of arrivals upto each time T

tau = randexp(Na,1,lam); % interarrival times, exp distributed
T = cumsum(tau); % Times at which arrivals occur (Arrival times)
NT = [1:length(T)]'; % Number of arrivals upto each time T

%% Plot the sample path of poisson process
% [T, NT] = poisson(10,1); % lam = 1/5/0.1/10
% figure()
% stairs(T,NT)
% axis([0 max(T+1) 0 max(NT)+1])
% title('Poisson Process for lambda = 10')
% ylabel('number of arrivals (N(t))')
% xlabel('arrival times: T')

% Since the values are only at discontinous points and no samples
% elsewhere, ensemble averages obtained wouldn't be proper due to lack of proper
% samples.

%% Plot the mean and autocovariance function using sample paths generated by poissrp.m
% [X,t] = poissrp(10000,[1:10],2);
% m_x = mean(X,1);
% autocov = mean((X - repmat(m_x,10000,1)).^2);
% plot(t,mean(X,1))
% axis([0 11 0 20])
% xlabel('time (t)')
% ylabel('mean of poisson process: lambda*time')
% title('mean of poisson process: lambda = 2')
% plot(t,autocov)
% axis([0 11 0 20])
% xlabel('time (t)')
% ylabel('Variance  of poisson process: lambda*time')
% title('Autocovariance of poisson process: lambda = 2')

% Theoretical functions discussed in the class match the empirical mean and
% autocovariance funtions.