function [X,t] = telerp(N,t,l)
%[X,t] = telerp(N,t,l)

% N : Number of sample paths to generate
% t : Vector of time points at which to generate samples
% l : Arrival rate. OPTIONAL. Default l=1.
% X : Matrix of process sample paths. Each row is a sample path, each column
%     is a different time point. 
%
% X(t) = Telegraph Random process with rate l
[Nt,t] = poissrp(N,t,l);
U = rand(N,length(t));
p = 0.5;
Z = U<p;
Z = double(Z);
Z(Z==0) = -1;
X = Z.* (-1).^Nt;

%% Plot the mean and autocovariance function using sample paths generated by telerp.m
% [X,t] = telerp(10,[0:10],2);
% figure()
% for i = 1:4
% hold on
% stairs(t,X(i,:))
% end
% axis([0 11 -1.5 1.5])
% xlabel('time (t)')
% ylabel('Telegraph process X(t)')
% title('Sample paths of a random telegraph wave')

% [X,t] = telerp(10000,[0:10],2);
% m_x = mean(X,1);
% autocov = mean((X - repmat(m_x,10000,1)).^2);
% plot(t,mean(X,1))
% axis([0 10 -1 1])
% xlabel('time (t)')
% ylabel('mean')
% title('mean of telegraph random process: lambda = 2')
% plot(t,autocov)
% axis([0 10 0.9 1.1])
% xlabel('time (t)')
% ylabel('Variance')
% title('Autocovariance of telegraph process: lambda = 2')